### PR TITLE
linestyle improvements

### LINKED ISSUE #93: Edge linestyles not always working
tl;dr: Using `edge_attr = (; linestyle = [...])` requires setting `edge_plottype = :beziersegments` too.

I was trying to use the `linestyle` edge attribute to represent edge types, but passing a `Vector{Symbol}` of line styles per edge sometimes caused plotting to fail:

```
ERROR: LoadError: MethodError: no method matching *(::Symbol, ::Float64)
[...]
Stacktrace:
  [1] _broadcast_getindex_evalf
    @ ./broadcast.jl:670 [inlined]
  [2] _broadcast_getindex
    @ ./broadcast.jl:643 [inlined]
  [3] getindex
    @ ./broadcast.jl:597 [inlined]
  [4] copy
    @ ./broadcast.jl:899 [inlined]
  [5] materialize(bc::Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(*), Tuple{Vector{Symbol}, Float64}})
    @ Base.Broadcast ./broadcast.jl:860
  [6] (::GLMakie.var"#189#190"{GLMakie.Screen{GLFW.Window}, Makie.Scene, MakieCore.LineSegments{Tuple{Vector{GeometryBasics.Point{2, Float32}}}}})(gl_attributes::Dict{Symbol, Any})
    @ GLMakie ~/.julia/packages/GLMakie/x68HK/src/drawing_primitives.jl:278
[...]
```

After investigating, I noticed that this only happens if there are no double- or self-edges in the graph. The reason is that in these cases (or if the graph is too large), `edge_plottype = Makie.automatic` makes GraphMakie choose `Makie.linesegments!` to plot the edges, which interprets the `Vector` as defining a single `linestyle` pattern to be used for all the edges. (That behavior is undocumented for `Makie.linesegments`, though the `Makie.lines` documentation has an example.) The GraphMakie `beziersegments!` recipe, on the other hand, works as expected because [it lifts the properties itself](https://github.com/MakieOrg/GraphMakie.jl/blob/061addf41458ea676cdf1e956df90932389f8b2b/src/recipes.jl#L589). Therefore, a workaround (for smaller graphs) is to explicitly set `edge_plottype = :beziersegments`.

Example:

```julia
using GraphMakie, GLMakie, Graphs

graphplot(
    DiGraph([Edge(1 => 2), Edge(2 => 1)]),
    edge_attr = (; linestyle = [:dot, :dash]),
)
# works

graphplot(
    DiGraph([Edge(1 => 2), Edge(2 => 3)]),
    edge_attr = (; linestyle = [:dot, :dash]),
)
# MethodError: no method matching *(::Symbol, ::Float64)

graphplot(
    DiGraph([Edge(1 => 2), Edge(2 => 3)]),
    edge_attr = (; linestyle = [:dot, :dash]),
    edge_plottype = :beziersegments,
)
# works
```

Conversely, using the `Float64[]` linestyle variant (defining a custom pattern) works in the `:linesegments` case, while for `:beziersegments` it depends on the number of nodes in the graph: if the pattern length is equal to `Graphs.nv`, the error is "Pattern needs to be a Vector of floats. Found: Float64", otherwise it seems to work.

This is not strictly a bug, because nothing promises that this should work (so feel free to close this), but I wanted to file this anyway because the behavior surprised me and it took me a while to understand what's going on.

My preferred solution would be [`Makie.linesegments` accepting a vector of linestyles](https://github.com/MakieOrg/Makie.jl/issues/1598), but otherwise maybe GraphMakie should plot individual `Makie.lines` and lift the properties like in the bezier case to ensure consistency?

### PR DESCRIPTION
**Pull request by hexaeder**
attempt to close #93

I figured #93 has two parts:
- `linestyles<:Vector` does not work for `linesegments`. I don't like to automaticially use `beziersegments` in that case. But the error explains that option now. I added a `@test_broken` item so hopefully we will notice if the corresponding makie issue gets resolved: https://github.com/MakieOrg/Makie.jl/issues/1598
- `linestyles<:Vector{Number}` should not be split among edges if it happens to be the same length as the number of edges. I added a codepath to handle that case.

### CODE REVIEW

File: test/runtests.jl [hunk 1]
```diff
@@ -242,4 +242,31 @@ end
...
+    @test_throws ArgumentError graphplot(
+        DiGraph([Edge(1 => 2), Edge(2 => 3)]),
+        edge_attr = (; linestyle = [:dot, :dash]),
+    )
+
+    graphplot(
+        DiGraph([Edge(1 => 2), Edge(2 => 3)]),
+        edge_attr = (; linestyle = [:dot, :dash]),
+        edge_plottype = :beziersegments,
+    )
```
Comment (lmshk) [inline test/runtests.jl:263]: Maybe add one with curves just to be safe? (`[Edge(1 => 2), Edge(2 => 1)]` like above.)

**Review by lmshk — APPROVED** [review]
Thanks for taking care of this!
